### ISSUE TITLE
Beyond validation - introspecting the schema

### ISSUE THREAD

**Issue by ciscoheat** [decs/typeschema#9]
Hi, thank you for a nice initiative to standardize a very fragmented area of the ecosystem. I'd like to get some ideas about how to build upon and improve the simple and useful API you have right now. 

I'd love to use typeschema with [Superforms](https://superforms.rocks/), and in the future v2.0 be able to hook into any validation library. Right now only Zod is supported, which wasn't a random pick, it's a great library but also pretty much the only one I could find that goes beyond validation and has some important features for a comprehensive form library like Superforms.

You can read the details here: https://github.com/ciscoheat/sveltekit-superforms/issues/120, but in essence I'm looking for a couple of additional things for a validation library:

**A.** Being able to introspect the schema types, to figure out the following about a schema field:

- its type (the real or "underlying" type, since it can be hidden behind wrappers as in Zod with `ZodEffect`)
- if its optional
- if its nullable
- its default value, if it exists

This allows Superforms to create default values for a schema, so you can do something like:

```ts
const form = await superValidate(schema);
```

Which will amongst other return an object with default values for the schema, so type-safety is ensured.

Another piece of data returned from `superValidate` is `constraints`, which takes us into the next level of introspection:

**B.** Introspect the specific validators on a schema field.

Given a Zod schema like this:

```ts
z.string().min(3).regex(/^\w+$/)
```

You can look into all validators and generate [html validation constraints](https://developer.mozilla.org/en-US/docs/Learn/Forms/Form_validation#using_built-in_form_validation) based upon them, so in this case:

```ts
{
  min: 3,
  pattern: '^\w+$'
  required: true
}
```

This object can then be spread on an html input field, and we have browser validation without requiring javascript.

I'm not really up to speed with the other libraries, so my question is, do you know if some of them have the possibility to handle A and B? A feature matrix would be awesome, then I can make a decision if it's worth pursuing this for v2.0. 

It depends on how many libraries can handle case A basically. B is nice to have, but A is pretty much required, unless the library supports default values and the consumer want to supply their own for every field, which is a bit tedious. So maybe the matrix would be:

| Project                                            | Default values | A. Type introspection | B. Validator introspection |
| -------------------------------------------------- | -------------- | --------------------- | -------------------------- |
| [zod](https://zod.dev)                             |  ✅             | ✅                  | ✅                       |
| [yup](https://github.com/jquense/yup)              |                |                    |                         | 
| [joi](https://joi.dev)                             |                |                    |                         | 
| [ajv](https://ajv.js.org)                          |                |                    |                         | 
| [superstruct](https://docs.superstructjs.org)      |                |                    |                         | 
| [io-ts](https://gcanti.github.io/io-ts)            |                |                    |                         | 
| [ow](https://sindresorhus.com/ow)                  |                |                    |                         | 
| [typebox](https://github.com/sinclairzx81/typebox) |                |                    |                         | 
| [typia](https://typia.io)                          |                |                    |                         | 
| [deepkit](https://deepkit.io)                      |                |                    |                         | 
| [runtypes](https://github.com/pelotom/runtypes)    |                |                    |                         | 
| [arktype](https://arktype.io)                      |                |                    |                         | 

Let me know what you think, thanks for any help you can give. :)

**Comment by ssalbdivad** [comment]
> A. Being able to introspect the schema types, to figure out the following about a schema field:
>    its type (the real or "underlying" type, since it can be hidden behind wrappers as in Zod with ZodEffect)
>    if its optional
>    if its nullable
>    its default value, if it exists

Unfortunately, these attributes are pretty tightly coupled to the way Zod represents types, so they can't really form the basis of a common API layer the way a standard like HTML validation constraints could.

Realistically, the most validator-agnostic way to provide introspectable types is probably just compiling to something like JSON schema. I'm not sure whether this work would be done in the individual libraries (ArkType does have [an issue for that]), in typeschema, or some combination, but it would likely be a fairly significant undertaking for most to do completely.

**Comment by thelinuxlich** [comment]
Yeah, I think typematic from @ecyrbe would benefit from this too

**Comment by ecyrbe** [comment]
Hello @ciscoheat ,

not all libraries have support for defaults, but some have.
Introspection of libraries is in contrast to what @ssalbdivad said is definitely possible for some of them.
Just need to add a generic adapter iterator for those that support it. We added adapters with André, and it's a powerfull tool to allow this kind of feature.
It's a lot of work though, but i'm needing this for zodios and typematic like @thelinuxlich said.
So i might try to go down the rabbit home to implement it.

**Comment by ssalbdivad** [comment]
@ecyrbe The problem is if you define your own format for introspectable types you've essentially just created another opinionated runtime type representation and bumped the problem up one level.

Sure, you'd have adapters for common validators, but what if someone else doesn't like your type representation or has other features they need? They create their own representation with adapters, then you need a meta-adapter for the adapter libraries (relevant xkcd: https://xkcd.com/927/) 🤣

Any introspectable type representation is going to be opinionated by nature, so I think the only way to avoid this problem is just having a common standard that supports existing tooling like JSON schema.

**Comment by ecyrbe** [comment]
@ssalbdivad i'm pretty sure you can have an instrospectable instropection. I implemented some in C++ back in the day. Like you have json schema standard being itself descriptible with json schema.
You can do the same for discovering the features you need.
It's an `embrace them all` approach instead of a `use common denominator` like json schema.
But like i said, it's a lot of work, so i keep the warning in mind.

**Comment by ssalbdivad** [comment]
@ecyrbe It still feels like creating a common denominator, it's just something new, no?

Having a self-definable schema also doesn't solve the problem of it being opinionated.

Maybe it will all work out and become the new standard, but how to represent types is something I've thought about probably more than any other problem and it's extremely nuanced if you want it to be robust. At a high level, ArkType has branches at the top level, then predicates (intersections of constraints of various kinds). Each of those constraint kinds has its own format to ensure these is only one correct representation of a type so that they can be easily compared ("make illegal states unrepresentable").

I don't think JSON schema does a particularly good job at these things and is not well-suited as an operand for type operations, but it feels like it's either settle for a suboptimal common standard or build a fundamentally better one. To me, it felt like building a better one was fundamental to ArkType's type system, but in terms of integrations with other libraries, I think it will be much easier to just support a subset of ArkType's type system that can be compiled to JSON schema as opposed to trying to get everyone to adopt it as a standard (at least for the foreseeable future).

**Comment by ciscoheat** [comment]
For form validation, I'm hoping that a small set of types is enough since we're in a sense bound to the string limitation of input fields. Of course there can be numbers, and some object-like structures like `Date`, but they can have a simple string representation as primitives. And these *should* be enough for the introspection case A I'm talking about, right? And for case B, maybe building on the existing constraints standard is the way forward?

I'm glad to have all of you here - with your deep knowledge of the subject, I'm sure this cannot be an impossible problem to solve. Learning from the browser wars is my attitude, so something as fundamental as form validation won't turn into something similar.

**Comment by ssalbdivad** [comment]
I think the challenge will be determining which properties are critical to the standard, which could vary based on the needs of the library trying to consume it. Making these kinds of decisions is really hard, especially if you want to avoid having to revise them as new needs arise.

This is why I'd recommend leveraging existing established formats like JSON schema and HTML validation attributes. It won't be perfect, but it will absolve you of having to dictate which properties are supported, how they're specified, and evangelize that sufficiently for library authors to adopt it. As a bonus, you'd get immediate support for the libraries that innately support JSON Schema like [TypeBox](https://github.com/sinclairzx81/typebox).

I know @sinclairzx81 has also expressed some thoughts around JSON schema as a good underlying representation for TS validation constraints. While I don't think it's ideal as the basis of a type system, as a common representation across validation libraries it feels like the clearest answer.

**Comment by ciscoheat** [comment]
That's a great idea, and the TypeBox [schema definitions](https://github.com/sinclairzx81/typebox#standard-types) seems well thought-out. Now, how to get some consensus on this?

**Comment by ssalbdivad** [comment]
@ciscoheat To be clear, while I also think TypeBox is great it wouldn't be inherently related to the standard- the standard would just be [JSON schema itself](https://json-schema.org/) and/or the [builtin HTML validation attributes](https://developer.mozilla.org/en-US/docs/Learn/Forms/Form_validation#using_built-in_form_validation) you mentioned.

TypeBox is just an example of a validator that already supports JSON schema, so it would be fully compatible by default, and I know the author mentioned he had had reasonable success relying on JSON schema to represent some complex constraints.

If you want to move forward with JSON schema as the common underlying representation, I think the next step would be a group message to validation library authors asking if they officially support translation to/from JSON schema. If so, how is it used (if that's not already documented somewhere), and if not, do they plan to add support in the future.

**Comment by decs** [comment]
Released as part of `v0.13.0`. There's now a `toJSONSchema` function. Let's work on making all adapters compatible!

**Comment by ciscoheat** [comment]
Great news! I've been very busy with the v2 release, but now [Superforms](https://superforms.rocks/) has JSON Schema generators for Joi, TypeBox, Valibot, Yup and Zod. Some are external libraries, others are converted to ESM and included in the source. In a while I can start working on a PR to add them. There are some inconsistencies between them though, mostly in how dates are handled, that should be discussed in another issue first, perhaps.
